### ISSUE TITLE
purpose of the regex in setFile ?

### ISSUE THREAD

**Issue by divinity76** [michaeljs1990/jmem#2]
in this code

```php
	public function setFile($file) {
        $f = $file;
        if (preg_match('#^compress\.(.*)://(.*)#', $file, $r)) {
            $f = $r[2];
        }
```
what the heck is the regex doing?

**Comment by michaeljs1990** [comment]
https://github.com/michaeljs1990/jmem/commit/21738edebae6f05adccc11c74e45ff28d86c7dcf

was the commit that introduced this and was for files in the format seen here http://php.net/manual/en/wrappers.compression.php. I honestly didn't look much into it it looks like it should in reality use a different function to open the files however this hack just chops off the everything up to the start of the file.
